#! /bin/sh
### BEGIN INIT INFO
# Provides:          AFIBBoot
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      6
# Short-Description: AFIB Boot script.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

do_stop () {
        # Message should end with a newline since kFreeBSD may
        # print more stuff (see #323749)
        log_action_msg "Will now restart"
        reboot -d -f -i
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script AFIB"
	sh /home/pi/RPIAFIB/Bootscript/run.sh &
    ;;
  stop)
    echo "Stopping script AFIB"
#	killall python
#	killall sh
    ;;
  *)
    echo "Usage: /etc/init.d/AFIBBoot {start|stop}"
    exit 1
    ;;
esac

exit 0

